FROM golang:alpine

ENV APPNAME kitana

RUN apk add build-base abuild binutils git gcc musl-dev
RUN mkdir -p /go/src /go/bin /go/github.com/$APPNAME && chmod -R 777 /go

ENV GOPATH /go
ENV PATH /go/bin:$PATH

WORKDIR /go/github.com/$APPNAME

ADD . /go/github.com/$APPNAME

RUN go get github.com/gorilla/mux

CMD ["go", "test"]
